foreground = yes
debug = 5
output = /tmp/stunnel.log
pid = /tmp/stunnel.pid

[amqps-front]
accept = 0.0.0.0:5671
connect = 127.0.0.1:5672
cert = /workspaces/kombu/repro/tls/cert.pem
key  = /workspaces/kombu/repro/tls/key.pem
